// iOS device presets (iPhone family).
//
// Screen sizes are the logical CSS-px viewports Apple reports for each model.
// Chrome metrics are tuned to read as that device without claiming pixel-exact
// industrial dimensions.

import { evenBezel, type DevicePreset } from "./deviceTypes";

const IOS_FRAME_COLOR = "#1B1B1D";

export const IOS_DEVICES: DevicePreset[] = [
  {
    id: "iphone-15-pro-max",
    label: "iPhone 15 Pro Max",
    platform: "ios",
    screen: { width: 430, height: 932 },
    bezel: evenBezel(16),
    screenRadius: 55,
    frameRadius: 70,
    frameColor: "#2A2A2C",
    cutout: { kind: "dynamic-island", width: 122, height: 36, offsetTop: 11 },
    homeIndicator: true,
    homeButton: false,
    buttons: [
      { side: "left", offset: 120, length: 34, kind: "action" },
      { side: "left", offset: 175, length: 60, kind: "volume" },
      { side: "left", offset: 245, length: 60, kind: "volume" },
      { side: "right", offset: 195, length: 95, kind: "power" },
    ],
  },
  {
    id: "iphone-15-pro",
    label: "iPhone 15 Pro",
    platform: "ios",
    screen: { width: 393, height: 852 },
    bezel: evenBezel(15),
    screenRadius: 53,
    frameRadius: 67,
    frameColor: "#2A2A2C",
    cutout: { kind: "dynamic-island", width: 118, height: 35, offsetTop: 11 },
    homeIndicator: true,
    homeButton: false,
    buttons: [
      { side: "left", offset: 110, length: 32, kind: "action" },
      { side: "left", offset: 160, length: 56, kind: "volume" },
      { side: "left", offset: 224, length: 56, kind: "volume" },
      { side: "right", offset: 178, length: 88, kind: "power" },
    ],
  },
  {
    id: "iphone-15",
    label: "iPhone 15",
    platform: "ios",
    screen: { width: 393, height: 852 },
    bezel: evenBezel(16),
    screenRadius: 52,
    frameRadius: 68,
    frameColor: IOS_FRAME_COLOR,
    cutout: { kind: "dynamic-island", width: 118, height: 35, offsetTop: 11 },
    homeIndicator: true,
    homeButton: false,
    buttons: [
      { side: "left", offset: 150, length: 26, kind: "action" },
      { side: "left", offset: 188, length: 56, kind: "volume" },
      { side: "left", offset: 252, length: 56, kind: "volume" },
      { side: "right", offset: 200, length: 88, kind: "power" },
    ],
  },
  {
    id: "iphone-14-plus",
    label: "iPhone 14 Plus",
    platform: "ios",
    screen: { width: 428, height: 926 },
    bezel: evenBezel(16),
    screenRadius: 50,
    frameRadius: 66,
    frameColor: IOS_FRAME_COLOR,
    cutout: { kind: "notch", width: 162, height: 30 },
    homeIndicator: true,
    homeButton: false,
    buttons: [
      { side: "left", offset: 170, length: 50, kind: "volume" },
      { side: "left", offset: 234, length: 50, kind: "volume" },
      { side: "right", offset: 196, length: 86, kind: "power" },
    ],
  },
  {
    id: "iphone-14",
    label: "iPhone 14 / 13",
    platform: "ios",
    screen: { width: 390, height: 844 },
    bezel: evenBezel(16),
    screenRadius: 47,
    frameRadius: 63,
    frameColor: IOS_FRAME_COLOR,
    cutout: { kind: "notch", width: 156, height: 30 },
    homeIndicator: true,
    homeButton: false,
    buttons: [
      { side: "left", offset: 150, length: 48, kind: "volume" },
      { side: "left", offset: 212, length: 48, kind: "volume" },
      { side: "right", offset: 176, length: 82, kind: "power" },
    ],
  },
  {
    id: "iphone-13-mini",
    label: "iPhone 13 mini",
    platform: "ios",
    screen: { width: 375, height: 812 },
    bezel: evenBezel(15),
    screenRadius: 44,
    frameRadius: 59,
    frameColor: IOS_FRAME_COLOR,
    cutout: { kind: "notch", width: 150, height: 28 },
    homeIndicator: true,
    homeButton: false,
    buttons: [
      { side: "left", offset: 142, length: 46, kind: "volume" },
      { side: "left", offset: 200, length: 46, kind: "volume" },
      { side: "right", offset: 168, length: 78, kind: "power" },
    ],
  },
  {
    id: "iphone-se",
    label: "iPhone SE",
    platform: "ios",
    screen: { width: 375, height: 667 },
    bezel: { top: 78, right: 12, bottom: 96, left: 12 },
    screenRadius: 4,
    frameRadius: 44,
    frameColor: "#0E0E0F",
    cutout: { kind: "none" },
    homeIndicator: false,
    homeButton: true,
    earpiece: true,
    buttons: [
      { side: "left", offset: 150, length: 44, kind: "volume" },
      { side: "left", offset: 208, length: 44, kind: "volume" },
      { side: "right", offset: 150, length: 70, kind: "power" },
    ],
  },
];
